### ISSUE TITLE
Provide a SDK to create a portapp 

### ISSUE THREAD

**Issue by user12w** [portapps/portapps#324] opened 2023-09-23 10:00 UTC
"I plan to provide an SDK to allow everyone to develop a portapp. Its development will be carried out on this repository."

When are you finally going to do it? At least approximately.

**Comment by crazy-max** [comment] 2023-11-04 09:51
duplicate of https://github.com/portapps/portapps/issues/90

**Closed by crazy-max** 2023-11-04 09:51 UTC
