### ISSUE TITLE
Discord Canary

### ISSUE THREAD

**Issue by evman** [portapps/portapps#367] opened 2024-07-29 17:31 UTC
### Request guidelines

- [X] I've read the [request guidelines](https://portapps.io/doc/request-app/)

### I've checked that that ...

- [X] ... license allows distribution/repackaging of the software
- [X] ... this is not an abdandonware

### Name

Discord Canary

### Description

Portable version of Discord Canary. Stable and PTB are already supported, figure Canary would be a quick and easy addon.  Installation files can be found in website link below. Thank you!

### Website

https://support.discord.com/hc/en-us/articles/360035675191-Discord-Testing-Clients

### License

https://discord.com/licenses

### TOS link

https://discord.com/terms

**Comment by crazy-max** [comment] 2024-11-12 22:13
duplicate of https://github.com/portapps/portapps/issues/193

**Closed by crazy-max** 2024-11-12 22:13 UTC
Labels: :package: app request
